# Dependencies
highlighter:      rouge

gems:
  - jekyll-paginate
  - jekyll-feed

# Permalinks
permalink:              /blog/:categories/:title/
# permalink:            blog/:categories/:year/:month/:day/:title/

# Setup
title:            'Mayank Gupta'
name:             'Mayank Gupta'
#tagline:          ''
description:      'Mechanical Engineer, Creative Technologist'
#url:             
baseurl:
# blogurl:          /blog/


author:
  name:           'Mayank Gupta'
  url:            mayankgupta.gq
  email:          'mayankg.1997@gmail.com'
  github:         'https://github.com/arcruiton'
  facebook:       'http://www.facebook.com/knayamgupta'
  twitter:        'https://twitter.com/mayank1997gupta'
  googleplus:     'https://plus.google.com/u/0/+MayankGupta79'
  linkedin:       'https://www.linkedin.com/in/knayamgupta'

paginate:         3
# paginate_path:    "/blog/page:num/"

# Custom vars
version:          2.1.0


# defaults:
#   -
#     scope:
#       path: ""
#       type: "projects" # a collection in your site, in plural form
#     values:
#       layout: "default"
